// src/main.js
import {
  auth,
  onAuthStateChanged,
  signInAnonymously
} from "./services/firebase.js";
import {
  normalizeApprovalMap
} from "./core/approvals.js";
import {
  getPlayerCodeSalt as getPlayerAccessCodeSalt,
  getRememberedAdminCode as getStoredAdminCode,
  getRememberedPlayerCode as getStoredPlayerCode,
  isAdminCodeValid as isAdminAccessCodeValid,
  isPlayerCodeValid as isPlayerAccessCodeValid,
  rememberPlayerCode as storePlayerCode
} from "./room/access-codes.js";
import {
  normalizeIncomingDealPrompt as normalizeDealPrompt
} from "./core/deal-prompts.js";
import { createSeatIdentityFlow } from "./room/seat-identity-flow.js";
import { createSetupLobbyFlow } from "./room/setup-lobby-flow.js";
import { createRoomSessionFlow } from "./room/room-session-flow.js";
import { createGameSyncFlow } from "./room/game-sync-flow.js";
import { createApprovalLabels } from "./room/approval-labels.js";
import { createTableScreenController } from "./table/table-screen-controller.js";
import { createTableManagerFlow } from "./table/table-manager-flow.js";
import { createTableSaveFlow } from "./table/table-save-flow.js";
import {
  showAppAlert,
  showAppConfirm
} from "./ui/dialogs.js";
import {
  createButton,
  createParagraph
} from "./ui/ui-dom.js";
import { normalizeRotationOffset } from "./table/table-layout.js";
import {
  loadTableViewRotation as loadStoredTableViewRotation,
  saveTableViewRotation as saveStoredTableViewRotation
} from "./table/table-view-preferences.js";
import {
  transactRoom
} from "./room/room-sync.js";
import {
  normalizeIncomingPlayer,
  normalizeIncomingPlayers,
  normalizeIncomingPots,
  normalizeSelectedWinnersByPot,
  normalizeSettlementPreview
} from "./room/room-state.js";
import { createHandPlayFlow } from "./game/hand-play-flow.js";
import { createStartGameFlow } from "./game/start-game-flow.js";
import {
  normalizeInviteToken,
  normalizeJoinRequests
} from "./room/room-entry.js";
import {
  getPlayerCompactIdentityLabel as formatPlayerCompactIdentityLabel,
  getPlayerIdentityLabel as formatPlayerIdentityLabel,
  getPlayerName as getPlayerDisplayName,
  getRawPlayerName as getPlayerRawName,
  hasDuplicatePlayerName as hasDuplicatePlayerDisplayName,
  isAutoSeatName as isAutoGeneratedSeatName,
  shouldUseRequestNameForSeat as shouldUseRequestNameForPlayerSeat
} from "./core/player-model.js";
import { createSettlementFlow } from "./game/settlement-flow.js";
import { createNextHandFlow } from "./game/next-hand-flow.js";
import {
  canClientControlPlayerInRoom as canClientControlPlayerInRoomData,
  canClientManageRoomData as canClientManageRoomPayload,
  getCurrentDevicePlayer as getCurrentDevicePlayerFromList,
  getCurrentDevicePlayerIndex as getCurrentDevicePlayerIndexFromList,
  getHostClientId as getRoomSessionHostClientId,
  getPlayerControllerId as getRoomPlayerControllerId,
  getRoomManagerProxyId as getRoomManagerProxyClientId,
  isClientAdminInRoom as isClientAdminInRoomData,
  isCurrentDevicePlayer as isCurrentDevicePlayerInList
} from "./room/room-permissions.js";
import {
  ROOM_MODES,
  createMembersMap,
  getClientId,
  getRoomHostId,
  normalizeAdminPlayerIds,
  normalizeMembers,
  normalizePlayerOwnerId,
  normalizeRoomMode
} from "./room/identity.js";
import {
  canPlayerRaise as canPlayerRaiseWithState,
  getCallAmount as calculateCallAmount,
  getChipStep as calculateChipStep,
  getDefaultRaiseTarget as calculateDefaultRaiseTarget,
  getEligiblePlayerIndices as collectEligiblePlayerIndices,
  getMaximumRaiseTarget as calculateMaximumRaiseTarget,
  getMinimumRaiseTarget as calculateMinimumRaiseTarget,
  getPotSizedRaiseTarget as calculatePotSizedRaiseTarget,
  getRaiseUnavailableMessage as getRaiseUnavailableMessageForState,
  getRaiseValidation as validateRaiseTarget
} from "./core/game-rules.js";
import { initGuidePanels } from "./ui/guide.js";
import { initChipRiffle } from "./riffle/riffle.js";

// ----------------------
// 全局变量及 DOM 获取
// ----------------------
let players = [];
let currentPlayerIndex = -1;
let pot = 0;               // 累积奖池
let currentBet = 0;        // 本轮最大下注
let lastRaiseSize = 20;    // 本轮最近一次完整下注/加注幅度
let currentRound = 0;      // 0-翻牌前、1-翻牌后、2-转牌、3-河牌
const rounds = ["翻牌前", "翻牌后", "转牌", "河牌"];

const setupContainer = document.getElementById("setup");
const gameContainer = document.getElementById("game");
const playerNameInputsContainer = document.getElementById("player-names");
const startGameBtn = document.getElementById("start-game");
const addPlayerBtn = document.getElementById("add-player");
const initialChipsInput = document.getElementById("initial-chips");
const bigBlindInput = document.getElementById("big-blind");
const roomIdInput = document.getElementById("room-id");
const playerAliasInput = document.getElementById("player-alias");
const copyInviteBtn = document.getElementById("copy-invite");
const localModeBtn = document.getElementById("local-mode");
const roomModeBtn = document.getElementById("room-mode");
const createRoomBtn = document.getElementById("create-room");
const joinRoomBtn = document.getElementById("join-room");
const roomEntry = document.getElementById("room-entry");
const deviceIdentityEl = document.getElementById("device-identity");
const gameLog = document.getElementById("game-log");
const handActions = document.getElementById("hand-actions");
const tableViewToolbar = document.getElementById("table-view-toolbar");
const logSummary = document.getElementById("log-summary");
const showdownPanel = document.getElementById("showdown-panel");
const dealPromptPanel = document.getElementById("deal-prompt-panel");
const settlementPreviewPanel = document.getElementById("settlement-preview-panel");
const tableManagerBackdrop = document.getElementById("table-manager-backdrop");
const tableManagerPanel = document.getElementById("table-manager-panel");
const syncStatusEl = document.getElementById("sync-status");
const riffleTrigger = document.querySelector(".brand-mark-button");

initGuidePanels();
initChipRiffle({ trigger: riffleTrigger });

let bigBlind = 20;
let smallBlind = 10;

let gameOver = false;
let gameStarted = false;
let awaitingShowdown = false;
let pendingPots = [];
let selectedWinnersByPot = {};
let pendingDealPrompt = null;
let settlementPreview = null;
let nextHandApprovals = {};
let stateVersion = 0;
let handId = 0;
let handStatus = "setup";
let mutationInProgress = false;
let syncReady = false;
let syncWriteInProgress = false;
let batchingStateUpdate = false;
let tableViewRotationOffset = 0;

const MAX_PLAYERS = 10;
let clientId = getClientId();
let authReady = false;
let authUnavailable = false;

// ----------------------
// 房间系统数据结构
// ----------------------
let room = {
  roomId: "",
  mode: ROOM_MODES.local,
  operator: clientId,
  hostClientId: clientId,
  inviteToken: "",
  adminKeyHash: "",
  adminPlayerIds: [],
  joinRequests: {},
  members: createMembersMap(clientId),
  players: [],
  gameState: {
    currentRound: 0,
    pot: 0,
    currentBet: 0,
    lastRaiseSize: 20,
    currentPlayerIndex: -1,
    logs: [],
    inProgress: false,
    gameOver: false,
    awaitingShowdown: false,
    pendingPots: [],
    selectedWinnersByPot: {},
    pendingDealPrompt: null,
    settlementPreview: null,
    nextHandApprovals: {},
    handId: 0,
    handStatus: "setup",
    stateVersion: 0,
    updatedBy: clientId
  }
};

let setupLobbyFlow;
let roomSessionFlow;
let gameSyncFlow;
let handPlayFlow;
let settlementFlow;
let nextHandFlow;
let tableSaveFlow;
let startGameFlow;

const seatIdentityFlow = createSeatIdentityFlow({
  getState: () => ({
    players,
    room,
    clientId,
    handStatus
  }),
  modes: {
    isRoomMode
  },
  permissions: {
    isCurrentDevicePlayer,
    getCurrentDevicePlayer,
    canCurrentClientManageRoom,
    canClientManageRoomData
  },
  labels: {
    getPlayerIdentityLabel
  },
  access: {
    getRememberedPlayerCode,
    rememberPlayerCode,
    getPlayerCodeSalt,
    isPlayerCodeValid
  },
  remote: {
    updateRoomMemberPresence: (...args) => roomSessionFlow?.updateMemberPresence(...args),
    setMutationInProgress,
    setSyncStatus,
    refreshFromRemote: (...args) => roomSessionFlow?.refreshFromRemote(...args),
    setSyncReady: value => {
      syncReady = Boolean(value);
    },
    inferHandStatus,
    getRoomHostId,
    normalizeRoomMode
  },
  applyLocalClaimResult: result => {
    players = result.players;
    room.members = result.members;
    if (result.resetNextHandApprovals) nextHandApprovals = {};
    room.players = players;
  },
  setLocalJoinRequest: (requestClientId, request) => {
    room.joinRequests = {
      ...normalizeJoinRequests(room.joinRequests),
      [requestClientId]: request
    };
  },
  refreshUi: {
    getAliasInputValue: () => playerAliasInput?.value || "",
    setAliasInputValue: value => {
      if (playerAliasInput) playerAliasInput.value = value;
    },
    renderIdentityControls,
    renderTableManagerIfOpen: () => tableManagerFlow.renderIfOpen(),
    renderSetupPlayerInputs: () => setupLobbyFlow?.renderPlayers(),
    updatePlayerBoxes,
    renderTableViewToolbar
  }
});

const approvalLabels = createApprovalLabels({
  getState: () => ({
    players,
    room,
    clientId
  }),
  identity: {
    getPlayerControllerId,
    getHostClientId
  },
  labels: {
    getPlayerCompactIdentityLabel,
    getClientShortId
  }
});

setupLobbyFlow = createSetupLobbyFlow({
  elements: {
    playerNameInputsContainer,
    startGameBtn,
    addPlayerBtn,
    initialChipsInput,
    bigBlindInput
  },
  maxPlayers: MAX_PLAYERS,
  getState: () => ({
    players,
    room,
    clientId,
    bigBlind,
    handId,
    handStatus,
    stateVersion,
    gameStarted,
    authReady,
    syncWriteInProgress
  }),
  mutations: {
    setPlayers: nextPlayers => {
      players = nextPlayers;
      room.players = players;
    },
    setRoom: nextRoom => {
      room = nextRoom;
    },
    setStateVersion: nextStateVersion => {
      stateVersion = nextStateVersion;
    },
    setSyncWriteInProgress: inProgress => {
      syncWriteInProgress = Boolean(inProgress);
    },
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    }
  },
  modes: {
    isRoomMode,
    isLocalMode
  },
  permissions: {
    canCurrentClientManageRoom,
    canCurrentClientEditRoomSettings,
    canCurrentClientModifyClaims,
    isCurrentDevicePlayer,
    canClientManageRoomData
  },
  identity: {
    getSetupClaimLabel,
    togglePlayerClaim,
    touchMemberWithProfile
  },
  remote: {
    transactRoom,
    refreshFromRemote: (...args) => roomSessionFlow?.refreshFromRemote(...args),
    getRoomHostId,
    inferHandStatus
  },
  ui: {
    showAppAlert,
    setSyncStatus,
    renderIdentityControls
  },
  helpers: {
    mergePlayerIdentityFields,
    normalizeAdminPlayerIds,
    normalizeJoinRequests
  }
});

roomSessionFlow = createRoomSessionFlow({
  elements: {
    roomIdInput,
    playerAliasInput,
    copyInviteBtn,
    localModeBtn,
    roomModeBtn,
    createRoomBtn,
    joinRoomBtn
  },
  getState: () => ({
    room,
    clientId,
    gameStarted,
    syncReady
  }),
  mutations: {
    setRoom: nextRoom => {
      room = nextRoom;
    },
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    },
    setHandId: nextHandId => {
      handId = nextHandId;
    },
    setHandStatus: nextHandStatus => {
      handStatus = nextHandStatus;
    }
  },
  modes: {
    isLocalMode,
    isRoomMode
  },
  identity: {
    touchMemberWithProfile,
    rememberPreferredDisplayName,
    getPreferredDisplayName
  },
  setup: {
    renderPlayers: () => setupLobbyFlow.renderPlayers(),
    sync: (...args) => setupLobbyFlow.sync(...args)
  },
  remote: {
    applyRoomData
  },
  ui: {
    showAppAlert,
    setSyncStatus,
    renderIdentityControls,
    updatePlayerBoxes,
    loadTableViewRotation,
    refreshInteractiveControls
  },
  helpers: {
    createMembersMap
  }
});

gameSyncFlow = createGameSyncFlow({
  getState: () => ({
    room,
    players,
    currentRound,
    pot,
    currentBet,
    lastRaiseSize,
    currentPlayerIndex,
    gameOver,
    awaitingShowdown,
    pendingPots,
    selectedWinnersByPot,
    pendingDealPrompt,
    settlementPreview,
    nextHandApprovals,
    handId,
    handStatus,
    stateVersion,
    clientId,
    batchingStateUpdate
  }),
  mutations: {
    setRoom: nextRoom => {
      room = nextRoom;
    },
    setStateVersion: nextStateVersion => {
      stateVersion = nextStateVersion;
    },
    setSyncWriteInProgress: inProgress => {
      syncWriteInProgress = Boolean(inProgress);
    },
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    }
  },
  remote: {
    transactRoom,
    getRemoteGameState: () => roomSessionFlow.getRemoteGameState(),
    refreshFromRemote: () => roomSessionFlow.refreshFromRemote()
  },
  ui: {
    setSyncStatus,
    refreshInteractiveControls
  },
  helpers: {
    inferHandStatus,
    mergePlayerIdentityFields,
    normalizeRoomMode,
    getRoomHostId,
    normalizeAdminPlayerIds,
    normalizeJoinRequests,
    normalizeMembers,
    touchMemberWithProfile
  }
});

handPlayFlow = createHandPlayFlow({
  getState: () => ({
    players,
    currentPlayerIndex,
    pot,
    currentBet,
    lastRaiseSize,
    currentRound,
    rounds,
    bigBlind,
    smallBlind,
    handId,
    handStatus,
    gameOver,
    awaitingShowdown,
    pendingDealPrompt,
    stateVersion,
    mutationInProgress,
    room,
    clientId
  }),
  mutations: {
    applyState: patch => {
      if ("players" in patch) {
        players = patch.players;
        room.players = players;
      }
      if ("currentPlayerIndex" in patch) currentPlayerIndex = patch.currentPlayerIndex;
      if ("pot" in patch) pot = patch.pot;
      if ("currentBet" in patch) currentBet = patch.currentBet;
      if ("lastRaiseSize" in patch) lastRaiseSize = patch.lastRaiseSize;
      if ("currentRound" in patch) currentRound = patch.currentRound;
      if ("selectedWinnersByPot" in patch) selectedWinnersByPot = patch.selectedWinnersByPot;
      if ("pendingDealPrompt" in patch) pendingDealPrompt = patch.pendingDealPrompt;
      if ("settlementPreview" in patch) settlementPreview = patch.settlementPreview;
      if ("nextHandApprovals" in patch) nextHandApprovals = patch.nextHandApprovals;
      if ("pendingPots" in patch) pendingPots = patch.pendingPots;
      if ("awaitingShowdown" in patch) awaitingShowdown = patch.awaitingShowdown;
      if ("gameOver" in patch) gameOver = patch.gameOver;
      if ("handStatus" in patch) handStatus = patch.handStatus;
    },
    setMutationInProgress,
    setBatchingStateUpdate: inProgress => {
      batchingStateUpdate = Boolean(inProgress);
    }
  },
  labels: {
    getPlayerIdentityLabel
  },
  rules: {
    getRaiseState
  },
  permissions: {
    canCurrentClientControlPlayer,
    canClientControlPlayerInRoom,
    isSharedPromptActionLocked,
    canCurrentClientConfirmDeal
  },
  remote: {
    getRemoteGameState: () => roomSessionFlow.getRemoteGameState(),
    updateFirebaseState
  },
  ui: {
    showAppAlert,
    showAppConfirm,
    hideShowdownPanel,
    hideDealPromptPanel,
    hideSettlementPreviewPanel,
    renderDealPromptPanel,
    clearHandActions,
    showNextHandButton,
    updateGameInfo,
    updatePlayerBoxes,
    updateGameLog
  },
  actions: {
    beginShowdown,
    awardRemainingPot,
    getPlayerById,
    inferHandStatus
  }
});

settlementFlow = createSettlementFlow({
  getState: () => ({
    players,
    pot,
    bigBlind,
    handId,
    handStatus,
    stateVersion,
    pendingPots,
    selectedWinnersByPot,
    settlementPreview,
    awaitingShowdown,
    clientId,
    room
  }),
  mutations: {
    applyState: patch => {
      if (!patch) return;
      if ("players" in patch) {
        players = patch.players;
        room.players = players;
      }
      if ("pot" in patch) pot = patch.pot;
      if ("currentBet" in patch) currentBet = patch.currentBet;
      if ("lastRaiseSize" in patch) lastRaiseSize = patch.lastRaiseSize;
      if ("currentPlayerIndex" in patch) currentPlayerIndex = patch.currentPlayerIndex;
      if ("awaitingShowdown" in patch) awaitingShowdown = patch.awaitingShowdown;
      if ("pendingPots" in patch) pendingPots = patch.pendingPots;
      if ("selectedWinnersByPot" in patch) selectedWinnersByPot = patch.selectedWinnersByPot;
      if ("pendingDealPrompt" in patch) pendingDealPrompt = patch.pendingDealPrompt;
      if ("settlementPreview" in patch) settlementPreview = patch.settlementPreview;
      if ("nextHandApprovals" in patch) nextHandApprovals = patch.nextHandApprovals;
      if ("gameOver" in patch) gameOver = patch.gameOver;
      if ("handStatus" in patch) handStatus = patch.handStatus;
    },
    setMutationInProgress,
    setBatchingStateUpdate: inProgress => {
      batchingStateUpdate = Boolean(inProgress);
    },
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    }
  },
  labels: {
    getPlayerIdentityLabel
  },
  permissions: {
    isInteractionLocked,
    isSharedPromptActionLocked,
    isRoomMode
  },
  approvals: approvalLabels,
  remote: {
    isRemoteHandStill,
    updateFirebaseState,
    transactRoom,
    refreshFromRemote: () => roomSessionFlow.refreshFromRemote()
  },
  ui: {
    showAppAlert,
    setSyncStatus,
    hideShowdownPanel,
    hideDealPromptPanel,
    renderDealPromptPanel,
    hideSettlementPreviewPanel,
    renderSettlementPreviewPanel,
    renderShowdownPanel,
    clearHandActions,
    showNextHandButton,
    updateGameInfo,
    updatePlayerBoxes,
    updateGameLog
  },
  actions: {
    getPlayerById,
    inferHandStatus
  }
});

nextHandFlow = createNextHandFlow({
  getState: () => ({
    players,
    room,
    clientId,
    handId,
    handStatus,
    stateVersion,
    gameOver,
    nextHandApprovals,
    bigBlind,
    mutationInProgress
  }),
  mutations: {
    applyState: patch => {
      if ("players" in patch) {
        players = patch.players;
        room.players = players;
      }
      if ("currentRound" in patch) currentRound = patch.currentRound;
      if ("currentBet" in patch) currentBet = patch.currentBet;
      if ("lastRaiseSize" in patch) lastRaiseSize = patch.lastRaiseSize;
      if ("pot" in patch) pot = patch.pot;
      if ("currentPlayerIndex" in patch) currentPlayerIndex = patch.currentPlayerIndex;
      if ("pendingPots" in patch) pendingPots = patch.pendingPots;
      if ("selectedWinnersByPot" in patch) selectedWinnersByPot = patch.selectedWinnersByPot;
      if ("pendingDealPrompt" in patch) pendingDealPrompt = patch.pendingDealPrompt;
      if ("settlementPreview" in patch) settlementPreview = patch.settlementPreview;
      if ("nextHandApprovals" in patch) nextHandApprovals = patch.nextHandApprovals;
      if ("awaitingShowdown" in patch) awaitingShowdown = patch.awaitingShowdown;
      if ("gameOver" in patch) gameOver = patch.gameOver;
      if ("handId" in patch) handId = patch.handId;
      if ("handStatus" in patch) handStatus = patch.handStatus;
    },
    setMutationInProgress,
    setBatchingStateUpdate: inProgress => {
      batchingStateUpdate = Boolean(inProgress);
    },
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    },
    setRoomGameInProgress: inProgress => {
      room.gameState.inProgress = Boolean(inProgress);
    }
  },
  permissions: {
    isLocalMode,
    isRoomMode,
    isInteractionLocked
  },
  approvals: approvalLabels,
  rules: {
    getEligiblePlayerIndices
  },
  remote: {
    transactRoom,
    refreshFromRemote: () => roomSessionFlow.refreshFromRemote(),
    isRemoteHandStill,
    updateFirebaseState
  },
  ui: {
    showAppAlert,
    setSyncStatus,
    renderNextHandButton,
    clearGameLog,
    clearHandActions,
    hideShowdownPanel,
    hideDealPromptPanel,
    hideSettlementPreviewPanel
  },
  actions: {
    inferHandStatus,
    startRound
  }
});

tableSaveFlow = createTableSaveFlow({
  maxPlayers: MAX_PLAYERS,
  getState: () => ({
    players,
    room,
    clientId,
    handStatus,
    handId,
    stateVersion
  }),
  mutations: {
    setPlayers: nextPlayers => {
      players = nextPlayers;
      room.players = players;
    },
    setRoom: nextRoom => {
      room = nextRoom;
    },
    setNextHandApprovals: approvals => {
      nextHandApprovals = approvals;
    },
    setMutationInProgress,
    setBatchingStateUpdate: inProgress => {
      batchingStateUpdate = Boolean(inProgress);
    }
  },
  permissions: {
    canCurrentClientManageRoom,
    canClientManageRoomData
  },
  rules: {
    getEligiblePlayerIndices
  },
  remote: {
    transactRoom,
    refreshFromRemote: () => roomSessionFlow.refreshFromRemote(),
    updateFirebaseState
  },
  setup: {
    renderPlayers: () => setupLobbyFlow.renderPlayers(),
    updateActionState: () => setupLobbyFlow.updateActionState(),
    sync: (...args) => setupLobbyFlow.sync(...args)
  },
  ui: {
    showAppAlert,
    closeTableManager: () => tableManagerFlow.close(),
    renderTableManagerIfOpen: () => tableManagerFlow.renderIfOpen(),
    updatePlayerBoxes,
    updateGameLog
  },
  helpers: {
    mergePlayerIdentityFields
  }
});

const tableManagerFlow = createTableManagerFlow({
  elements: {
    backdrop: tableManagerBackdrop,
    panel: tableManagerPanel
  },
  maxPlayers: MAX_PLAYERS,
  getState: () => ({
    players,
    room,
    handStatus,
    handId,
    stateVersion
  }),
  getInitialChips: () => toPositiveInteger(initialChipsInput.value, 1000),
  canEditTableNow: () => tableSaveFlow.canEditTableNow(),
  isSharedPromptActionLocked,
  isLocalMode,
  isRoomMode,
  getEligiblePlayerIndices,
  labels: {
    getPlayerIdentityLabel
  },
  identity: {
    getCurrentDevicePlayer,
    canCurrentClientManageRoom,
    getCurrentDisplayName,
    getGuestDisplayName,
    getPendingJoinRequestCount,
    getCurrentRoomRoleLabel,
    getClientShortId
  },
  actions: {
    releaseCurrentPlayerIdentity,
    copyInviteLink: (...args) => roomSessionFlow.copyInviteLink(...args),
    saveCurrentDisplayName,
    setSyncStatus,
    approveSeatRequest,
    declineSeatRequest,
    togglePlayerClaim,
    togglePlayerAdmin,
    createPlayerId: () => setupLobbyFlow.createPlayerId(),
    removeAdminPlayerId,
    commitTableDraft,
    approveNextHandStart
  },
  formatters: {
    getPlayerName,
    getSavedPlayer: playerId => players.find(item => item.id === playerId),
    isCurrentDevicePlayer,
    getClientShortId,
    getJoinRequestsForPlayer
  }
});

const tableScreen = createTableScreenController({
  elements: {
    handActions,
    showdownPanel,
    dealPromptPanel,
    settlementPreviewPanel
  },
  maxPlayers: MAX_PLAYERS,
  getState: () => ({
    players,
    currentPlayerIndex,
    pot,
    currentBet,
    bigBlind,
    currentRound,
    rounds,
    gameOver,
    awaitingShowdown,
    pendingPots,
    selectedWinnersByPot,
    pendingDealPrompt,
    settlementPreview,
    nextHandApprovals,
    handId,
    handStatus,
    tableViewRotationOffset,
    clientId
  }),
  modes: {
    isLocalMode,
    isRoomMode
  },
  permissions: {
    isInteractionLocked,
    isSharedPromptActionLocked,
    canCurrentClientControlPlayer,
    canCurrentClientConfirmDeal,
    canCurrentClientManageRoom,
    getCurrentDevicePlayerIndex,
    isCurrentDevicePlayer,
    canCurrentClientModifyClaims
  },
  labels: {
    getPlayerIdentityLabel,
    getPlayerCompactIdentityLabel,
    getSetupClaimLabel
  },
  betting: {
    getCallAmount,
    getCallButtonLabel,
    canPlayerRaise,
    getMinimumRaiseTarget,
    getMaximumRaiseTarget,
    getDefaultRaiseTarget,
    getPotSizedRaiseTarget,
    getRaiseValidation,
    getChipStep,
    getEligiblePlayerIndices
  },
  approvals: approvalLabels,
  actions: {
    playerAction,
    confirmDealPrompt,
    openTableManager,
    approveNextHandStart,
    togglePlayerClaim,
    getPlayerById,
    toggleWinner,
    buildSettlementPlan,
    confirmShowdown,
    cancelSettlementPreview,
    confirmSettlementPreview
  }
});

startGameFlow = createStartGameFlow({
  elements: {
    startGameBtn,
    roomIdInput,
    bigBlindInput
  },
  maxPlayers: MAX_PLAYERS,
  getState: () => ({
    players,
    room,
    clientId,
    handId,
    mutationInProgress
  }),
  mutations: {
    applyRoomPatch: patch => {
      room = {
        ...room,
        ...patch
      };
    },
    applyStartState: patch => {
      players = patch.players;
      bigBlind = patch.bigBlind;
      smallBlind = patch.smallBlind;
      selectedWinnersByPot = {};
      pendingDealPrompt = null;
      settlementPreview = null;
      nextHandApprovals = {};
      pendingPots = [];
      awaitingShowdown = false;
      handId = patch.handId;
      handStatus = "playing";
      gameStarted = true;
      gameOver = false;
      currentRound = 0;
      currentBet = 0;
      lastRaiseSize = bigBlind;
      pot = 0;
      room.players = players;
      room.gameState.inProgress = true;
    },
    setMutationInProgress,
    setSyncReady: ready => {
      syncReady = Boolean(ready);
    }
  },
  modes: {
    isRoomMode
  },
  permissions: {
    canCurrentClientManageRoom
  },
  remote: {
    remoteRoomExists: (...args) => roomSessionFlow.remoteRoomExists(...args),
    createRoomIfAvailable: (...args) => roomSessionFlow.createRoomIfAvailable(...args),
    joinRoom: (...args) => roomSessionFlow.joinRoom(...args),
    refreshFromRemote: (...args) => roomSessionFlow.refreshFromRemote(...args),
    getRemoteGameState: (...args) => roomSessionFlow.getRemoteGameState(...args),
    stopListener: (...args) => roomSessionFlow.stopListener(...args)
  },
  setup: {
    normalizePlayers: () => setupLobbyFlow.normalizePlayers(),
    createPlayerId: () => setupLobbyFlow.createPlayerId()
  },
  ui: {
    showAppAlert,
    setSyncStatus,
    clearGameLog,
    showGameTable: () => {
      setupContainer.style.display = "none";
      gameContainer.style.display = "grid";
    },
    clearHandActions,
    hideShowdownPanel,
    hideDealPromptPanel,
    hideSettlementPreviewPanel
  },
  actions: {
    inferHandStatus,
    startRound
  }
});

// ----------------------
// 通用工具函数
// ----------------------
function toNonNegativeNumber(value, fallback = 0) {
  const number = Number(value);
  return Number.isFinite(number) && number >= 0 ? number : fallback;
}

function toPositiveInteger(value, fallback = 0) {
  const number = parseInt(value, 10);
  return Number.isFinite(number) && number > 0 ? number : fallback;
}

function getPlayerName(player) {
  return getPlayerDisplayName(player);
}

function getRawPlayerName(player) {
  return getPlayerRawName(player);
}

function isAutoSeatName(name = "") {
  return isAutoGeneratedSeatName(name);
}

function shouldUseRequestNameForSeat(player, index = players.indexOf(player)) {
  return shouldUseRequestNameForPlayerSeat(player, index);
}

function getClientShortId(value = clientId) {
  return seatIdentityFlow.getClientShortId(value);
}

function getPreferredDisplayName(roomId = room.roomId) {
  return seatIdentityFlow.getPreferredDisplayName(roomId);
}

function rememberPreferredDisplayName(name, roomId = room.roomId) {
  seatIdentityFlow.rememberPreferredDisplayName(name, roomId);
}

function normalizeDisplayName(name = "") {
  return seatIdentityFlow.normalizeDisplayName(name);
}

function getCurrentMemberDisplayName(actorClientId = clientId) {
  return seatIdentityFlow.getCurrentMemberDisplayName(actorClientId);
}

function getCurrentDisplayName() {
  return seatIdentityFlow.getCurrentDisplayName();
}

function getGuestDisplayName(actorClientId = clientId) {
  return seatIdentityFlow.getGuestDisplayName(actorClientId);
}

async function saveCurrentDisplayName(rawName, { announce = true } = {}) {
  return seatIdentityFlow.saveCurrentDisplayName(rawName, { announce });
}

function getJoinRequestForClient(actorClientId = clientId) {
  return seatIdentityFlow.getJoinRequestForClient(actorClientId);
}

function getJoinRequestsForPlayer(playerId) {
  return seatIdentityFlow.getJoinRequestsForPlayer(playerId);
}

function getPendingJoinRequestCount() {
  return seatIdentityFlow.getPendingJoinRequestCount();
}

function touchMemberWithProfile(existingMembers = room.members, actorClientId = clientId, overrides = {}) {
  return seatIdentityFlow.touchMemberWithProfile(existingMembers, actorClientId, overrides);
}

function getRememberedAdminCode(roomId = room.roomId) {
  return getStoredAdminCode(roomId);
}

function rememberPlayerCode(playerId, code, roomId = room.roomId) {
  storePlayerCode(playerId, code, roomId);
}

function getRememberedPlayerCode(playerId, roomId = room.roomId) {
  return getStoredPlayerCode(playerId, roomId);
}

function getPlayerCodeSalt(playerId, roomId = room.roomId) {
  return getPlayerAccessCodeSalt(playerId, roomId);
}

function isPlayerCodeValid(player, code, roomData = room) {
  return isPlayerAccessCodeValid(player, code, roomData.roomId || room.roomId);
}

function isAdminCodeValid(code, roomData = room) {
  return isAdminAccessCodeValid(code, {
    ...roomData,
    roomId: roomData.roomId || room.roomId
  });
}

function getPlayerById(id) {
  return players.find(player => player.id === id);
}

function getActivePlayers() {
  return players.filter(player => !player.folded);
}

function isLocalMode() {
  return room.mode === ROOM_MODES.local;
}

function isRoomMode() {
  return room.mode === ROOM_MODES.room;
}

function needsRemoteSync() {
  return isRoomMode() && Boolean(room.roomId);
}

function rekeyRoomMember(previousClientId, nextClientId) {
  if (!previousClientId || !nextClientId || previousClientId === nextClientId) return;
  const members = normalizeMembers(room.members);
  const previousMember = members[previousClientId] || {};
  delete members[previousClientId];
  members[nextClientId] = {
    ...previousMember,
    clientId: nextClientId,
    lastSeenAt: Date.now()
  };
  room.members = members;
  players.forEach(player => {
    if (normalizePlayerOwnerId(player.ownerClientId) === previousClientId) {
      player.ownerClientId = nextClientId;
    }
  });
  if (room.operator === previousClientId) room.operator = nextClientId;
  if (room.hostClientId === previousClientId) room.hostClientId = nextClientId;
}

function applyAuthenticatedClientId(nextClientId) {
  const normalizedClientId = normalizePlayerOwnerId(nextClientId);
  if (!normalizedClientId || normalizedClientId === clientId) return;
  const previousClientId = clientId;
  clientId = normalizedClientId;
  rekeyRoomMember(previousClientId, clientId);
  room.members = touchMemberWithProfile(room.members, clientId);
  if (isLocalMode()) {
    room.operator = clientId;
    room.hostClientId = clientId;
  }
  refreshInteractiveControls();
  if (isRoomMode() && room.roomId) {
    roomSessionFlow.updateMemberPresence();
  }
}

function startAnonymousIdentity() {
  if (!auth) {
    authReady = true;
    authUnavailable = true;
    return;
  }
  onAuthStateChanged(auth, (user) => {
    authReady = true;
    if (user?.uid) {
      authUnavailable = false;
      applyAuthenticatedClientId(user.uid);
      if (isRoomMode() && room.roomId) {
        roomSessionFlow.stopListener();
        roomSessionFlow.listenFirebaseUpdates();
        roomSessionFlow.updateMemberPresence();
      }
      setSyncStatus(isRoomMode() && room.roomId ? "已连接身份" : "身份已就绪", "ok");
    }
    renderIdentityControls();
  });
  signInAnonymously(auth).catch(() => {
    authReady = true;
    authUnavailable = true;
    setSyncStatus(isRoomMode() && room.roomId ? "身份连接异常，房间同步以实际状态为准" : isRoomMode() ? "多人房间未连接" : "本地模式");
    renderIdentityControls();
  });
}

function getHostClientId(roomData = room) {
  return getRoomSessionHostClientId(roomData, {
    currentRoomId: room.roomId,
    localClientId: clientId
  });
}

function isClientAdminInRoom(actorClientId, roomData = room) {
  return isClientAdminInRoomData(actorClientId, roomData, {
    currentClientId: clientId,
    currentRoomId: room.roomId,
    players,
    isRememberedAdminCodeValid: (targetRoomData, currentRoomId) => {
      return isAdminCodeValid(getRememberedAdminCode(targetRoomData?.roomId || currentRoomId), targetRoomData);
    }
  });
}

function getRoomManagerProxyId(roomData = room) {
  return getRoomManagerProxyClientId(roomData, {
    currentRoomId: room.roomId,
    localClientId: clientId,
    players
  });
}

function canClientManageRoomData(actorClientId, roomData = room) {
  return canClientManageRoomPayload(actorClientId, roomData, {
    currentClientId: clientId,
    currentRoomId: room.roomId,
    players,
    isRememberedAdminCodeValid: (targetRoomData, currentRoomId) => {
      return isAdminCodeValid(getRememberedAdminCode(targetRoomData?.roomId || currentRoomId), targetRoomData);
    }
  });
}

function canClientControlPlayerInRoom(actorClientId, player, roomData = room) {
  return canClientControlPlayerInRoomData(actorClientId, player, roomData, {
    currentClientId: clientId,
    currentRoomId: room.roomId,
    players,
    isRememberedAdminCodeValid: (targetRoomData, currentRoomId) => {
      return isAdminCodeValid(getRememberedAdminCode(targetRoomData?.roomId || currentRoomId), targetRoomData);
    }
  });
}

function getCurrentDevicePlayerIndex(list = players) {
  return getCurrentDevicePlayerIndexFromList(list, clientId);
}

function getCurrentDevicePlayer(list = players) {
  return getCurrentDevicePlayerFromList(list, clientId);
}

function isCurrentDevicePlayer(player) {
  return isCurrentDevicePlayerInList(player, clientId);
}

function getPlayerControllerId(player, roomData = room) {
  return getRoomPlayerControllerId(player, roomData, {
    currentRoomId: room.roomId,
    localClientId: clientId,
    players
  });
}

function canCurrentClientControlPlayer(player) {
  return canClientControlPlayerInRoom(clientId, player, room);
}

function canCurrentClientManageRoom() {
  return canClientManageRoomData(clientId, room);
}

function canCurrentClientEditRoomSettings() {
  if (isLocalMode()) return true;
  if (!room.roomId) return true;
  return getHostClientId(room) === clientId;
}

function getCurrentRoomRoleLabel(roomData = room) {
  if (isLocalMode()) return "本地管理";
  if (getHostClientId(roomData) === clientId) return "房主";
  const currentPlayer = getCurrentDevicePlayer(roomData.players || players);
  if (currentPlayer && normalizeAdminPlayerIds(roomData.adminPlayerIds).includes(currentPlayer.id)) return "协管";
  if (canClientManageRoomData(clientId, roomData)) return "管理员";
  return "玩家";
}

function canCurrentClientModifyClaims() {
  return isRoomMode() && Boolean(room.roomId);
}

function getDealerPlayer() {
  return players.find(player => player.dealer) || null;
}

function canCurrentClientConfirmDeal() {
  return isLocalMode() || canCurrentClientControlPlayer(getDealerPlayer());
}

function hasDuplicatePlayerName(player, list = players) {
  return hasDuplicatePlayerDisplayName(player, list);
}

function getPlayerIdentityLabel(player, index = players.indexOf(player), list = players) {
  return formatPlayerIdentityLabel(player, index, list);
}

function getPlayerCompactIdentityLabel(player, index = players.indexOf(player), list = players) {
  return formatPlayerCompactIdentityLabel(player, index, list);
}

function getEligiblePlayerIndices(list = players) {
  return collectEligiblePlayerIndices(list);
}

function getCallAmount(player) {
  return calculateCallAmount(player, currentBet);
}

function getCallButtonLabel(player) {
  const callAmount = getCallAmount(player);
  if (callAmount <= 0) return "Call";
  if (player.chips < callAmount) return `All In ${player.chips}`;
  return `Call ${callAmount}`;
}

function getRaiseState() {
  return {
    currentBet,
    lastRaiseSize,
    bigBlind,
    smallBlind,
    pot,
    chipStep: getChipStep()
  };
}

function getRaiseUnavailableMessage(player) {
  return getRaiseUnavailableMessageForState(player, getRaiseState());
}

function canPlayerRaise(player) {
  return canPlayerRaiseWithState(player, getRaiseState());
}

function getChipStep() {
  return calculateChipStep(smallBlind, bigBlind);
}

function getMaximumRaiseTarget(player) {
  return calculateMaximumRaiseTarget(player);
}

function getMinimumRaiseTarget(player) {
  return calculateMinimumRaiseTarget(player, getRaiseState());
}

function getDefaultRaiseTarget(player) {
  return calculateDefaultRaiseTarget(player, getRaiseState());
}

function getPotSizedRaiseTarget(player, fraction) {
  return calculatePotSizedRaiseTarget(player, fraction, getRaiseState());
}

function getRaiseValidation(player, rawTarget) {
  return validateRaiseTarget(player, rawTarget, getRaiseState());
}

function addPendingRequestBadge(button, label, { floating = false } = {}) {
  const requestCount = getPendingJoinRequestCount();
  if (requestCount <= 0 || !canCurrentClientManageRoom()) return button;

  const badge = document.createElement("span");
  badge.className = "identity-request-badge";
  if (floating) {
    badge.classList.add("is-floating");
    button.classList.add("has-request-badge");
  }
  badge.textContent = requestCount > 9 ? "9+" : String(requestCount);
  button.appendChild(badge);
  button.setAttribute("aria-label", `${label}，${requestCount} 个待处理请求`);
  return button;
}

function clearGameLog() {
  gameLog.replaceChildren();
  room.gameState.logs = [];
  updateLogSummary();
}

function updateLogSummary() {
  if (!logSummary) return;
  const count = room.gameState.logs.length;
  logSummary.textContent = count > 0 ? `操作记录（${count}）` : "操作记录";
}

function setSyncStatus(message, status = "") {
  if (!syncStatusEl) return;
  syncStatusEl.textContent = message;
  syncStatusEl.classList.remove("ok", "error");
  if (status) syncStatusEl.classList.add(status);
}

function getTableViewRotationRoomId() {
  return room.roomId || "local";
}

function loadTableViewRotation() {
  tableViewRotationOffset = loadStoredTableViewRotation(getTableViewRotationRoomId());
}

function saveTableViewRotation() {
  saveStoredTableViewRotation(tableViewRotationOffset, getTableViewRotationRoomId());
}

function rotateTableView(delta) {
  tableViewRotationOffset += delta;
  saveTableViewRotation();
  updatePlayerBoxes();
  renderTableViewToolbar();
}

function resetTableViewRotation() {
  tableViewRotationOffset = 0;
  saveTableViewRotation();
  updatePlayerBoxes();
  renderTableViewToolbar();
}

function getIdentitySummaryText() {
  const currentPlayer = getCurrentDevicePlayer();
  const currentIndex = currentPlayer ? players.indexOf(currentPlayer) : -1;
  if (currentPlayer) {
    return `当前设备：${getPlayerIdentityLabel(currentPlayer, currentIndex)} · ${isRoomMode() ? `ID ${getClientShortId()}` : "本地控制"}`;
  }
  return isRoomMode()
    ? `当前设备未绑定玩家 · ID ${getClientShortId()}`
    : "本地模式：这台设备可以管理整桌";
}

function getIdentityAuthText() {
  if (isLocalMode()) return "";
  if (authUnavailable) {
    return syncReady ? "" : room.roomId ? "身份连接异常" : "";
  }
  return authReady ? "匿名身份" : "身份连接中";
}

function renderIdentityControls() {
  if (localModeBtn) {
    localModeBtn.classList.toggle("active", isLocalMode());
    localModeBtn.disabled = gameStarted && !isLocalMode();
  }
  if (roomModeBtn) {
    roomModeBtn.classList.toggle("active", isRoomMode());
    roomModeBtn.disabled = gameStarted && !isRoomMode();
  }
  if (roomEntry) roomEntry.hidden = !isRoomMode();
  const roomAuthPending = isRoomMode() && !authReady;
  if (createRoomBtn) createRoomBtn.disabled = gameStarted || syncWriteInProgress || roomAuthPending;
  if (joinRoomBtn) joinRoomBtn.disabled = gameStarted || syncWriteInProgress || roomAuthPending;
  if (copyInviteBtn) copyInviteBtn.disabled = !isRoomMode() || !room.roomId;
  if (playerAliasInput && document.activeElement !== playerAliasInput) {
    playerAliasInput.value = getCurrentDisplayName();
  }
  if (!deviceIdentityEl) return;

  deviceIdentityEl.replaceChildren();
  const title = document.createElement("strong");
  title.textContent = isRoomMode() ? "多人房间" : "单设备本地";
  const detail = document.createElement("span");
  const roomText = isRoomMode()
    ? room.roomId
      ? `房间 ${room.roomId} · ${Object.keys(room.members || {}).length || 1} 台设备${getPendingJoinRequestCount() ? ` · ${getPendingJoinRequestCount()} 个请求` : ""}`
      : "先创建或加入房间"
    : "不写入远程房间";
  const authText = getIdentityAuthText();
  detail.textContent = [getIdentitySummaryText(), roomText, authText].filter(Boolean).join(" · ");
  deviceIdentityEl.append(title, detail);
  if (isRoomMode() && room.roomId) {
    const manageButton = createButton("席位与身份", openTableManager, false, "identity-manage-button");
    addPendingRequestBadge(manageButton, "席位与身份");
    deviceIdentityEl.appendChild(manageButton);
  }
}

function renderTableViewToolbar() {
  if (!tableViewToolbar) return;
  tableViewToolbar.replaceChildren();
  if (!gameStarted) {
    tableViewToolbar.hidden = true;
    return;
  }

  tableViewToolbar.hidden = false;
  const summary = document.createElement("div");
  summary.className = "table-view-summary";
  const currentPlayer = getCurrentDevicePlayer();
  const currentIndex = currentPlayer ? players.indexOf(currentPlayer) : -1;
  const title = document.createElement("strong");
  title.textContent = currentPlayer
    ? `我的视角：${getPlayerIdentityLabel(currentPlayer, currentIndex)}`
    : isRoomMode()
      ? "旁观视角"
      : "本地整桌视角";
  const detail = document.createElement("span");
  detail.textContent = isRoomMode()
    ? "视角旋转只保存在这台设备"
    : "本地模式不绑定玩家身份";
  summary.append(title, detail);
  tableViewToolbar.appendChild(summary);

  if (!isRoomMode()) return;

  const controls = document.createElement("div");
  controls.className = "table-view-controls";
  const hasClaimedPlayer = Boolean(currentPlayer);
  const resetDisabled = !hasClaimedPlayer || normalizeRotationOffset(tableViewRotationOffset, players.length) === 0;
  controls.appendChild(createButton("↺", () => rotateTableView(-1), players.length < 2, "table-view-button"));
  controls.appendChild(createButton("以我为底", resetTableViewRotation, resetDisabled, "table-view-button"));
  controls.appendChild(createButton("↻", () => rotateTableView(1), players.length < 2, "table-view-button"));
  const identityButton = createButton("身份", openTableManager, false, "table-view-button");
  addPendingRequestBadge(identityButton, "身份", { floating: true });
  controls.appendChild(identityButton);
  tableViewToolbar.appendChild(controls);
}

function isInteractionLocked() {
  return mutationInProgress || syncWriteInProgress || (needsRemoteSync() && !syncReady);
}

function isSharedPromptActionLocked() {
  return mutationInProgress || syncWriteInProgress || (needsRemoteSync() && !syncReady);
}

function refreshInteractiveControls() {
  renderIdentityControls();
  updatePlayerBoxes();
  renderTableViewToolbar();
  renderDealPromptPanel();
  renderSettlementPreviewPanel();
  tableManagerFlow.renderIfOpen();

  if (handStatus === "waitingDeal") {
    hideShowdownPanel();
    clearHandActions();
  } else if (handStatus === "settlementPreview") {
    hideShowdownPanel();
    clearHandActions();
  } else if (awaitingShowdown) {
    renderShowdownPanel();
  } else if (gameOver) {
    renderNextHandButton();
  } else if (handStatus === "playing") {
    renderCurrentActionPanel();
  } else {
    clearHandActions();
  }
}

async function isRemoteHandStill(expectedHandId, allowedStatuses) {
  return gameSyncFlow.isRemoteHandStill(expectedHandId, allowedStatuses);
}

function setMutationInProgress(inProgress) {
  mutationInProgress = inProgress;
  refreshInteractiveControls();
}

async function updateFirebaseState(options = {}) {
  return gameSyncFlow.updateFirebaseState(options);
}

function appendLogMessage(message) {
  gameLog.appendChild(createParagraph(String(message)));
  gameLog.scrollTop = gameLog.scrollHeight;
}

function renderGameLog(logs) {
  gameLog.replaceChildren();
  logs.forEach(appendLogMessage);
  updateLogSummary();
}

function updateGameLog(message) {
  const safeMessage = String(message);
  room.gameState.logs.push(safeMessage);
  appendLogMessage(safeMessage);
  updateLogSummary();
}

function mergePlayerIdentityFields(nextPlayers, sourcePlayers = players, { preserveNames = false } = {}) {
  const sourceById = new Map(normalizeIncomingPlayers(sourcePlayers)
    .map(player => [player.id, player]));
  return normalizeIncomingPlayers(nextPlayers).map((player, index) => {
    const source = sourceById.get(player.id);
    if (!source) return player;
    const sourceName = getRawPlayerName(source);
    const nextName = getRawPlayerName(player);
    return {
      ...player,
      name: preserveNames && sourceName && (!nextName || shouldUseRequestNameForSeat(player, index))
        ? sourceName
        : player.name,
      ownerClientId: normalizePlayerOwnerId(source.ownerClientId),
      playerKeyHash: String(source.playerKeyHash || "")
    };
  });
}

function applyRoomData(data) {
  const gameState = data.gameState;
  currentRound = toNonNegativeNumber(gameState.currentRound, 0);
  pot = toNonNegativeNumber(gameState.pot, 0);
  currentBet = toNonNegativeNumber(gameState.currentBet, 0);
  lastRaiseSize = toPositiveInteger(gameState.lastRaiseSize, bigBlind);
  currentPlayerIndex = Number.isInteger(gameState.currentPlayerIndex)
    ? gameState.currentPlayerIndex
    : -1;
  gameOver = Boolean(gameState.gameOver);
  awaitingShowdown = Boolean(gameState.awaitingShowdown);
  pendingPots = normalizeIncomingPots(gameState.pendingPots);
  selectedWinnersByPot = normalizeSelectedWinnersByPot(gameState.selectedWinnersByPot);
  pendingDealPrompt = normalizeDealPrompt(gameState.pendingDealPrompt, { handId, roundCount: rounds.length });
  settlementPreview = normalizeSettlementPreview(gameState.settlementPreview, { handId });
  nextHandApprovals = normalizeApprovalMap(gameState.nextHandApprovals);
  handId = toNonNegativeNumber(gameState.handId, handId);
  handStatus = String(gameState.handStatus || inferHandStatus(gameState));
  stateVersion = toNonNegativeNumber(gameState.stateVersion, stateVersion);
  room.mode = normalizeRoomMode(data.mode, room.roomId);
  room.operator = String(data.operator || room.operator || clientId);
  room.hostClientId = getRoomHostId(data, room.operator || clientId);
  room.inviteToken = normalizeInviteToken(data.inviteToken || room.inviteToken || "");
  room.adminKeyHash = String(data.adminKeyHash || room.adminKeyHash || "");
  room.adminPlayerIds = normalizeAdminPlayerIds(data.adminPlayerIds);
  room.joinRequests = normalizeJoinRequests(data.joinRequests);
  room.members = touchMemberWithProfile(data.members, clientId);
  room.gameState.logs = Array.isArray(gameState.logs) ? gameState.logs.map(String) : [];
  room.gameState.inProgress = Boolean(gameState.inProgress);
  players = Array.isArray(data.players)
    ? data.players.map(normalizeIncomingPlayer)
    : players;
  room.players = players;
  tableManagerFlow.syncIdentityFromPlayers(players);

  renderIdentityControls();
  renderGameLog(room.gameState.logs);
  updateGameInfo();
  updatePlayerBoxes();
  renderTableViewToolbar();
  renderDealPromptPanel();
  renderSettlementPreviewPanel();

  if (handStatus === "waitingDeal") {
    hideShowdownPanel();
    clearHandActions();
  } else if (handStatus === "settlementPreview") {
    hideShowdownPanel();
    clearHandActions();
  } else if (awaitingShowdown) {
    renderShowdownPanel();
  } else {
    hideShowdownPanel();
  }

  if (gameOver && !awaitingShowdown) {
    renderNextHandButton();
  } else if (!gameOver && handStatus === "playing") {
    renderCurrentActionPanel();
  } else {
    clearHandActions();
  }

  if (gameState.inProgress === true) {
    setupContainer.style.display = "none";
    gameContainer.style.display = "grid";
    gameStarted = true;
  } else if (!gameStarted) {
    setupContainer.style.display = "block";
    gameContainer.style.display = "none";
    setupLobbyFlow.renderPlayers();
  }
}

if (playerAliasInput) {
  playerAliasInput.value = getCurrentDisplayName();
  playerAliasInput.addEventListener("change", async () => {
    await saveCurrentDisplayName(playerAliasInput.value, { announce: false });
  });
}

function isClaimedByOtherDevice(player) {
  return seatIdentityFlow.isClaimedByOtherDevice(player);
}

function getSetupClaimLabel(player) {
  return seatIdentityFlow.getSetupClaimLabel(player);
}

function applyLocalPlayerClaim(playerId, shouldClaim) {
  return seatIdentityFlow.applyLocalPlayerClaim(playerId, shouldClaim);
}

function getClaimAuthForPlayer(player, code = "", forceAdmin = false) {
  return seatIdentityFlow.getClaimAuthForPlayer(player, code, forceAdmin);
}

async function claimPlayerIdentity(playerId, { code = "", forceAdmin = false, announceCode = true } = {}) {
  await seatIdentityFlow.claimPlayerIdentity(playerId, { code, forceAdmin, announceCode });
}

async function releaseCurrentPlayerIdentity() {
  await seatIdentityFlow.releaseCurrentPlayerIdentity();
}

async function togglePlayerClaim(playerId) {
  await seatIdentityFlow.togglePlayerClaim(playerId);
}

function openDisplayNameRequestDialog({ playerId, title = "设置昵称后请求入座" } = {}) {
  seatIdentityFlow.openDisplayNameRequestDialog({ playerId, title });
}

async function requestSeatOwnership(playerId) {
  await seatIdentityFlow.requestSeatOwnership(playerId);
}

async function submitSeatOwnershipRequest(playerId, displayName) {
  await seatIdentityFlow.submitSeatOwnershipRequest(playerId, displayName);
}

async function approveSeatRequest(requestClientId) {
  await seatIdentityFlow.approveSeatRequest(requestClientId);
}

async function declineSeatRequest(requestClientId) {
  await seatIdentityFlow.declineSeatRequest(requestClientId);
}

startAnonymousIdentity();
roomSessionFlow.bindEntryControls();
roomSessionFlow.applyRoomLinkFromUrl();
setupLobbyFlow.init();
startGameFlow.bindStartButton();
syncReady = !isRoomMode();
if (!isRoomMode()) setSyncStatus("本地模式");
renderIdentityControls();

function findNextActionableIndex(startIndex, includeStart = false) {
  return handPlayFlow.findNextActionableIndex(startIndex, includeStart);
}

function getFirstActionIndexForRound(round = currentRound) {
  return handPlayFlow.getFirstActionIndexForRound(round);
}

function startRound() {
  handPlayFlow.startRound();
}

async function playerAction(action, index, amount = 0) {
  await handPlayFlow.playerAction(action, index, amount);
}

function nextPlayer() {
  handPlayFlow.nextPlayer();
}

function endRound() {
  handPlayFlow.endRound();
}

async function confirmDealPrompt() {
  await handPlayFlow.confirmDealPrompt();
}

function awardRemainingPot(winner) {
  settlementFlow.awardRemainingPot(winner);
}

function beginShowdown() {
  settlementFlow.beginShowdown();
}

function hideShowdownPanel() {
  tableScreen.hideShowdownPanel();
}

function hideDealPromptPanel() {
  tableScreen.hideDealPromptPanel();
}

function renderDealPromptPanel() {
  tableScreen.renderDealPromptPanel();
}

function hideSettlementPreviewPanel() {
  tableScreen.hideSettlementPreviewPanel();
}

function renderSettlementPreviewPanel() {
  tableScreen.renderSettlementPreviewPanel();
}

function renderShowdownPanel() {
  tableScreen.renderShowdownPanel();
}

function toggleWinner(potIndex, playerId) {
  settlementFlow.toggleWinner(potIndex, playerId);
}

function buildSettlementPlan() {
  return settlementFlow.buildSettlementPlan();
}

function getSettlementReportLines(preview) {
  return settlementFlow.getSettlementReportLines(preview);
}

function getPlayerIdentityLabelById(playerId, list = players) {
  return settlementFlow.getPlayerIdentityLabelById(playerId, list);
}

function getPlayerIdentityLabelsByIds(playerIds = [], list = players) {
  return settlementFlow.getPlayerIdentityLabelsByIds(playerIds, list);
}

function applySettlementFlowState(nextState) {
  settlementFlow.applyState(nextState);
}

async function confirmShowdown() {
  await settlementFlow.confirmShowdown();
}

async function cancelSettlementPreview() {
  await settlementFlow.cancelSettlementPreview();
}

async function confirmSettlementPreview() {
  await settlementFlow.confirmSettlementPreview();
}

async function approveSettlementPreview() {
  await settlementFlow.approveSettlementPreview();
}

async function finalizeSettlementPreview() {
  await settlementFlow.finalizeSettlementPreview();
}

// ----------------------
// 牌桌管理
// ----------------------
document.addEventListener("click", (event) => {
  tableScreen.closeSeatPopoversOnOutsideClick(event);
});

function canEditTableNow() {
  return tableSaveFlow.canEditTableNow();
}

function openTableManager() {
  tableManagerFlow.open();
}

function closeTableManager() {
  tableManagerFlow.close();
}

function removeAdminPlayerId(playerId) {
  tableSaveFlow.removeAdminPlayerId(playerId);
}

async function togglePlayerAdmin(playerId, shouldGrant) {
  await tableSaveFlow.togglePlayerAdmin(playerId, shouldGrant);
}

async function commitTableDraft({
  nextPlayers: draftPlayers,
  startNextHand = false,
  baseHandId,
  baseStateVersion,
  summaryText
} = {}) {
  return tableSaveFlow.commitTableDraft({
    nextPlayers: draftPlayers,
    startNextHand,
    baseHandId,
    baseStateVersion,
    summaryText
  });
}

// ----------------------
// 下一局
// ----------------------
async function approveNextHandStart(expectedHandId = handId) {
  await nextHandFlow.approveNextHandStart(expectedHandId);
}

async function resetHand(expectedHandId = handId) {
  await nextHandFlow.resetHand(expectedHandId);
}

function renderNextHandButton() {
  tableScreen.renderNextHandButton();
}

function clearHandActions() {
  tableScreen.clearHandActions();
}

function showNextHandButton() {
  tableScreen.showNextHandButton();
}

function inferHandStatus(gameState) {
  if (gameState.pendingDealPrompt) return "waitingDeal";
  if (gameState.settlementPreview) return "settlementPreview";
  if (gameState.awaitingShowdown) return "showdown";
  if (gameState.gameOver) return "settled";
  if (gameState.inProgress) return "playing";
  return "setup";
}

// ----------------------
// UI 更新
// ----------------------
function getRoundDisplayText() {
  return tableScreen.getRoundDisplayText();
}

function updateGameInfo() {
  tableScreen.updateGameInfo();
}

function renderCurrentActionPanel() {
  tableScreen.renderCurrentActionPanel();
}

function updatePlayerBoxes() {
  tableScreen.updatePlayerBoxes();
}

// 将核心函数导出到全局作用域，方便浏览器控制台调试
window.playerAction = playerAction;
window.resetHand = resetHand;
// End of file
